#!/bin/bash

if [ ${UID} =ne 0 ]
then
echo
echo "you need root access"
echo
exit 1
fi
##check number of processors
 
C='nproc'

 if [ ${c} -eq 1]
 then
	 echo "this sever is very small"
	 exit 2
 fi

 # checking memory
 free -m
